config/routes.rb
Rails.application.routes.draw do
 
  resources :sessions, only: %i[new create destroy]
  resources :users
  resources :blogs
  resources :favorites, only: %i[create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, presence: true
    validates :content, length: { in: 0..200 } 
    validates :content, presence: false
    belongs_to  :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites,source: :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
  validates :user_id, presence: true  
  validates :blog_id, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: {maximum: 20}, uniqueness: true
    validates :email, presence: true, length: {maximum: 255},
      format: {with: /\A[\w.!#$%&'*+\/=?^`{|}~-]+@[\w.-]+\.[\w-]+\z/i},
      uniqueness: true
    before_validation {email.downcase!}
    has_secure_password
    validates :password, length: {minimum: 6}, allow_nil: true
    has_many :blogs
    has_many :favorites, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery with: :exception
 include SessionsHelper
 before_action :login_required    
 private
      
 def login_required
 redirect_to new_session_path unless current_user
     end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
   
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog=Blog.new(blog_params)
    @blog.user_id= current_user.id
    # @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render :new
    else
    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
   end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content,)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_path, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_path, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
     session[:user_id] = user.id
     redirect_to user, notice: "ログインしました!"
    else
     flash[:danger] = "メールアドレス、パスワードが間違っています。"
     render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:danger] = "ログアウトしました!"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[new create]
  before_action :set_user, only: %i[show edit update destroy favorites]
  before_action :check_user, only: %i[edit update destroy]
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "アカウント作成しました!"
    else
      render :new
    end
  end
  def show
    @blog=@user.blogs
    favorites = Favorite.where(user_id: current_user.id).pluck(:blog_id)
    @favorite_blogs = Blog.find(favorites)
  end
  def edit
  end
  def update
    if @user.update(user_params)
      redirect_to @user, notice: "ユーザー情報を編集しました!"
    else
      render :edit
    end
  end
  def destroy
    @user.destroy
    flash[:danger] = "退会しました!"
    redirect_to new_user_path
  end
  private
  def user_params
    params.require(:user).permit(:name, :email,
      :password, :password_confirmation,:title,:content)
  end
  def set_user
    @user = User.find(params[:id])
  end
  def check_user
    if @user.id != current_user.id
      flash[:danger] = "編集できません!"
      redirect_back(fallback_location: @user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
     
    end
    def logged_in?
         current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= blog.user.name %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>
<p>Posted by:  <%= link_to @blog.user.name, user_path(@blog.user.id) %></p>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>
<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
      <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
      <%= link_to "All users", users_path %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_with(model: @user,url: user_path, local: true, class: "edit_form") do |form| %>
   <% if @user.errors.any? %>
    <div class="alert alert-danger alert-login">
     <h3><%= pluralize(@user.errors.count, "error", locale: :en)  %> prohibited this <%= @user.name %> from being saved:</h3>
     <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg%></li>
       <% end %>
    </ul>
   </div>
   <% end %>
    <table >
    <ul>
      <li>
       <%= @user.name %>
      </li>
      <li><%= form.label :name %>
       <%= form.text_field :name, class: "form-control", placeholder: t("views.users.name"), required: true %> </li>
      <li><%= form.label :email %></li>
       <li><%= form.email_field :email, class: "form-control", placeholder: t("views.users.email"), required: true %></li>
       <%= form.submit "update" %>
    </ul>
  </table>
 <% end %>

app/views/users/index.html.erb
 
<table>
 <tr>
    <th>ユーザー名前</th>
    <th>ユーザーemail</th>
    <th colspan="3"></th>
  </tr>
  <% @users.each do |user| %>
 <tr>
   
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= button_to "ユーザー詳細", user_path(user.id),method: :get %></td>
    <td><%= button_to 'ユーザー編集', edit_user_path(user.id),method: :get %></td>
    <td><%= button_to '削除',user_path(user.id), method: :delete ,data:{ confirm: '本当に削除していいですか？' } %></td>
   
    <% end %>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
お気に入り一覧
<ul>
<% if @favorite_blogs.present? %>
  <% @favorite_blogs.each do |blog| %>
  <li>  <%= blog.title %>
    <%= blog.content %> 
    <% end %></li>
<% end %>
</ul>

<p>メールアドレス: <%= @user.email %></p>
<br>
<%= button_to "create a blog", blogs_path,method: :get %>